name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add your steps here

    - name: Publish
      run: dotnet publish ./API/API.csproj --configuration Release --output ./publish

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUPLISH_SECRET }}
          package: ./publish
