
#github action to deploy the apiStock app to azure

name: Deploy Stock API

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "app-stock-api-westeurpe-dev-001" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore ./API/API.csproj

      - name: Build
        run: dotnet build ./API/API.csproj --configuration Release --no-restore

        #publish the app
      - name: Publish
        run: dotnet publish ./API/API.csproj --configuration Release --output ./publish

        #deploy the app to azure
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUPLISH_PROFILE }}
          package: ./publish
    
